sudo: false
language: python
python:
- '3.5'
env:
  global:
  - SOURCE_BRANCH: master
  - TARGET_BRANCH: gh-pages
  - COMMIT_AUTHOR_EMAIL: marhje52@kth.se
  - secure: bYI0OqDW9wY9kjqFm5Jt53N2jJJ3sou2MgjKp/7WXnekryKFZkS3o64b7M+fN1Qb0dKTLIlVjyKq4I0cpR51a4kvfaCpgTmEmq51yp3i4CwkDPFbTdUsshkHsFg/L8bPyDfLy3hryd9YdED6UGKFq7oHdnvEbx5PCZQgcnJk/utdV9krwuZMKTTcCpiB1Z0RePdSNxlLD8q1tKJKjwHUEjpTewGbllggN/m0TKe3+rSDD8IAz0/Mo3rA+FNH5TecZNAiVHIaKNW+DPZcDuhVw9hMR5/T0hpSzIKvWPSmEXoMNOvQDtnrUx6w9Z3T+4g4J5Pigz4GQ/AsbMr56dXTmwtgyZTdXT3ge5EDkdxt0sI96YrutjSnlwDdAIWEzFDgPKaR2BEDfnyXO17WvKgMRdhHib+D79F54qW4WOY339Oe5YsdmGYNmgOcCH0MoAWK5zbI13PzDlfek5HXE4TXRmBOCMXYr3UDvwSVetRMNUzGOc46/kguLxK6BjCfYmqcqKZ6Dag3BDZKpKklrIRmfivAICFn5qRJXbOso6jit+vV6faqIrsfUOvwtiQJUetl+R9vLrf4YaH2iaoQcbWYlZGSgJ9J4ZZPcf8EHoMd29k8N+j6vZCmW4O4h6B3RqurjpYHAmfOvGTLpP2u3LN6Uw4hDVi5an0M+1IUZFbRuPA=
install: pip3 install -r requirements.txt
before_script:
- "./scripts/before"
script: "./scripts/test"
after_success:
- "./scripts/deploy"
before_install:
- openssl aes-256-cbc -K $encrypted_d65680b40eb9_key -iv $encrypted_d65680b40eb9_iv
  -in secrets.tar.enc -out secrets.tar -d
